# Generated by Django 4.0 on 2021-12-19 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('repo_link', models.FilePathField(allow_folders=True, blank=True, max_length=256, path=None, verbose_name='путь к репозиторию')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('involved_users', models.ManyToManyField(blank=True, help_text='Список участников проекта', to=settings.AUTH_USER_MODEL, verbose_name='участники')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('task', models.TextField(max_length=256, verbose_name='текст')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('author', models.ForeignKey(on_delete=models.SET('удален'), to='usersapp.user', verbose_name='автор')),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.project', verbose_name='основной проект')),
            ],
        ),
    ]
