# Generated by Django 4.0 on 2022-01-01 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('repo_link', models.FilePathField(allow_folders=True, blank=True, max_length=256, path=None, verbose_name='путь к репозиторию')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('task', models.TextField(max_length=256, verbose_name='текст')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
            ],
        ),
    ]
