# Generated by Django 4.0 on 2022-01-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
    ]
